
services:  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    
    ports:
      - '3000:80'   
    volumes:
      - ./frontend:/app/frontend
    
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app/backend/
      - ./backend/static:/static
    restart: always
    ports:
      - '8000:8000'
    
    environment:
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    
