
services:  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    
    ports:
      - '3000:80'
    env_file:
      ./frontend/.env    
    volumes:
      - ./frontend:/app/frontend
    
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app/backend/
      - ./backend/static:/static
    restart: always
    ports:
      - '8000:8000'
    
    env_file:
      ./backend/.env

    
