# Generated by Django 5.0.3 on 2024-03-23 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_rename_firstset_score_first_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameplayer",
            name="player_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_two",
                to="matches.player",
            ),
        ),
    ]
