# Generated by Django 5.0.3 on 2024-03-23 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_alter_gameplayer_player_two"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="home",
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_set", models.IntegerField()),
                ("second_set", models.IntegerField()),
                ("third_set", models.IntegerField(blank=True, null=True)),
                ("winner", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.game"
                    ),
                ),
                (
                    "player_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.player"
                    ),
                ),
                (
                    "player_two",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_two",
                        to="matches.player",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GamePlayer",
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
