# Generated by Django 5.0.3 on 2024-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0005_team_score_alter_game_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="winner",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
