# Generated by Django 5.0.3 on 2024-09-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0006_alter_team_winner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ("name",)},
        ),
    ]
