# Generated by Django 5.0.3 on 2024-04-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="category",
            field=models.CharField(
                choices=[("post", "Post"), ("gallery", "Gallery")], default="post"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
