# Generated by Django 5.0.3 on 2024-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_image_category_image_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
