# Generated by Django 5.0.3 on 2024-09-26 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
